# Generated by Django 3.1.5 on 2021-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='3', max_length=10),
        ),
    ]
