# Generated by Django 3.1.5 on 2021-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamsapp', '0002_auto_20210127_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=10, null=True),
        ),
    ]
