# Generated by Django 3.1.5 on 2021-02-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immovable_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='businessfirm',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='homestead',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='land',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='other',
            name='notesfile',
        ),
        migrations.CreateModel(
            name='NoteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notefield', models.FileField(blank=True, null=True, upload_to='immovable-files/')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='immovable_app.building')),
                ('businessFirm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_Firms', to='immovable_app.businessfirm')),
                ('homestead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homestead', to='immovable_app.homestead')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='immovable_app.land')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='immovable_app.other')),
            ],
        ),
    ]
