# Generated by Django 3.1.5 on 2021-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immovable_app', '0002_auto_20210208_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessfirm',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestead',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
