# Generated by Django 3.1.5 on 2021-03-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immovable_app', '0003_auto_20210212_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteField',
            new_name='NoteField_im',
        ),
    ]
