# Generated by Django 3.1.5 on 2021-02-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movable_app', '0002_auto_20210128_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_or_bankvalue',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='ornaments',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='other',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='share',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='notesfile',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='notesfile',
        ),
        migrations.AddField(
            model_name='cash_or_bankvalue',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ornaments',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles',
            name='signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NoteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notefield', models.FileField(blank=True, null=True, upload_to='immovable-files/')),
                ('Cash_or_bankvalue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cash_or_bankvalues', to='movable_app.cash_or_bankvalue')),
                ('Electronics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='movable_app.electronics')),
                ('Insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Insurances', to='movable_app.insurance')),
                ('Ornaments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ornaments', to='movable_app.ornaments')),
                ('Stocks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stocks', to='movable_app.stocks')),
                ('Vehicles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicles', to='movable_app.vehicles')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='movable_app.other')),
            ],
        ),
    ]
