# Generated by Django 3.1.5 on 2021-02-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movable_app', '0003_auto_20210221_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notefield',
            old_name='Cash_or_bankvalue',
            new_name='cash_or_bankvalue',
        ),
        migrations.RenameField(
            model_name='notefield',
            old_name='Electronics',
            new_name='electronics',
        ),
        migrations.RenameField(
            model_name='notefield',
            old_name='Insurance',
            new_name='insurance',
        ),
        migrations.RenameField(
            model_name='notefield',
            old_name='Ornaments',
            new_name='ornaments',
        ),
        migrations.RenameField(
            model_name='notefield',
            old_name='Stocks',
            new_name='stocks',
        ),
        migrations.RenameField(
            model_name='notefield',
            old_name='Vehicles',
            new_name='vehicles',
        ),
    ]
