# Generated by Django 3.1.5 on 2021-02-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movable_app', '0004_auto_20210221_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notefield',
            old_name='electronics',
            new_name='electronic',
        ),
        migrations.RenameField(
            model_name='notefield',
            old_name='ornaments',
            new_name='ornament',
        ),
        migrations.RemoveField(
            model_name='notefield',
            name='stocks',
        ),
        migrations.AddField(
            model_name='notefield',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='movable_app.stocks'),
        ),
        migrations.AlterField(
            model_name='notefield',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='movable_app.insurance'),
        ),
        migrations.AlterField(
            model_name='notefield',
            name='vehicles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='movable_app.vehicles'),
        ),
    ]
