# Generated by Django 3.1.5 on 2021-02-21 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movable_app', '0005_auto_20210221_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other',
            new_name='Other_m',
        ),
        migrations.RemoveField(
            model_name='notefield',
            name='other',
        ),
        migrations.AddField(
            model_name='notefield',
            name='other_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_m', to='movable_app.other_m'),
        ),
    ]
