# Generated by Django 3.1.5 on 2021-02-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movable_app', '0006_auto_20210222_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefield',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='movable_app.share'),
        ),
    ]
